version: '3.7'
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
