default: &default
  adapter: postgresql
  encoding: unicode
  pool: 8
  username: root
  password:
  #host: 127.0.0.1

development:
  <<: *default
  database: gitstar_ranking

test:
  <<: *default
  database: gitstar_ranking_test

production:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV.fetch('POOL_SIZE', '4') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'gitstar_ranking') %>
